folder_in: /Users/the_ryuk/Desktop/PythonCurse_2/Progect_linux_curse/folder_in
folder_out: /Users/the_ryuk/Desktop/PythonCurse_2/Progect_linux_curse/folder_out
folder_ext: /Users/the_ryuk/Desktop/PythonCurse_2/Progect_linux_curse/folder_ext
folder_ext2: /Users/the_ryuk/Desktop/PythonCurse_2/Progect_linux_curse/folder_ext2